"""Reference phrases for the multilingual OCR harness."""

CASES = [
    ("es", "Español", "Hola, ¿cómo estás?"),
    ("en", "Inglés", "Hello, how are you?"),
    ("fr", "Francés", "Bonjour, comment allez-vous ?"),
    ("de", "Alemán", "Hallo, wie geht es dir?"),
    ("it", "Italiano", "Ciao, come stai?"),
    ("pt", "Portugués", "Olá, como estás?"),
    ("nl", "Neerlandés", "Hallo, hoe gaat het met je?"),
    ("sv", "Sueco", "Hej, hur mår du?"),
    ("no", "Noruego", "Hei, hvordan har du det?"),
    ("da", "Danés", "Hej, hvordan har du det?"),
    ("fi", "Finés", "Hei, mitä kuuluu?"),
    ("is", "Islandés", "Halló, hvernig hefurðu það?"),
    ("ga", "Irlandés", "Dia dhuit, conas atá tú?"),
    ("cy", "Galés", "Helo, sut wyt ti?"),
    ("pl", "Polaco", "Cześć, jak się masz?"),
    ("cs", "Checo", "Ahoj, jak se máš?"),
    ("sk", "Eslovaco", "Ahoj, ako sa máš?"),
    ("sl", "Esloveno", "Živjo, kako si?"),
    ("hr", "Croata", "Bok, kako si?"),
    ("sr", "Serbio", "Здраво, како си?"),
    ("bs", "Bosnio", "Zdravo, kako si?"),
    ("sr-Latn", "Montenegrino", "Zdravo, kako si?"),
    ("mk", "Macedonio", "Здраво, како си?"),
    ("bg", "Búlgaro", "Здравей, как си?"),
    ("ru", "Ruso", "Привет, как ты?"),
    ("uk", "Ucraniano", "Привіт, як ти?"),
    ("be", "Bielorruso", "Прывітанне, як ты?"),
    ("lt", "Lituano", "Labas, kaip sekasi?"),
    ("lv", "Letón", "Sveiki, kā jums klājas?"),
    ("et", "Estonio", "Tere, kuidas sul läheb?"),
    ("hu", "Húngaro", "Szia, hogy vagy?"),
    ("ro", "Rumano", "Salut, ce mai faci?"),
    ("sq", "Albanés", "Përshëndetje, si je?"),
    ("el", "Griego", "Γεια σου, πώς είσαι;"),
    ("tr", "Turco", "Merhaba, nasılsın?"),
    ("mt", "Maltés", "Bongu, kif int?"),
    ("hy", "Armenio", "Բարև, ինչպե՞ս ես։"),
    ("ka", "Georgiano", "გამარჯობა, როგორ ხარ?"),
    ("az", "Azerí", "Salam, necəsən?"),
    ("he", "Hebreo", "שלום, מה שלומך?"),
    ("ar", "Árabe", "مرحبا، كيف حالك؟"),
    ("fa", "Persa", "سلام، حالت چطوره؟"),
    ("ps", "Pastún", "سلام، څنګه یې؟"),
    ("ur", "Urdu", "ہیلو، آپ کیسے ہیں؟"),
    ("hi", "Hindi", "नमस्ते, आप कैसे हैं?"),
    ("bn", "Bengalí", "হ্যালো, আপনি কেমন আছেন?"),
    ("pa", "Punyabí", "ਸਤ ਸ੍ਰੀ ਅਕਾਲ, ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ?"),
    ("gu", "Gujarati", "નમસ્તે, તમે કેમ છો?"),
    ("mr", "Maratí", "नमस्कार, तुम्ही कसे आहात?"),
    ("ne", "Nepalí", "नमस्ते, तपाईंलाई कस्तो छ?"),
    ("ta", "Tamil", "வணக்கம், நீங்கள் எப்படி இருக்கிறீர்கள்?"),
    ("te", "Telugu", "నమస్కారం, మీరు ఎలా ఉన్నారు?"),
    ("kn", "Canarés", "ನಮಸ್ಕಾರ, ನೀವು ಹೇಗಿದ್ದೀರಿ?"),
    ("ml", "Malayalam", "നമസ്കാരം, സുഖമാണോ?"),
    ("si", "Cingalés", "ආයුබෝවන්, ඔබට කොහොමද?"),
    ("th", "Tailandés", "สวัสดี คุณเป็นอย่างไรบ้าง?"),
    ("lo", "Lao", "ສະບາຍດີ, ເຈົ້າເປັນແນວໃດ?"),
    ("km", "Jemer", "សួស្តី តើអ្នកសុខសប្បាយជាទេ?"),
    ("my", "Birmano", "မင်္ဂလာပါ၊ နေကောင်းလား။"),
    ("zh-CN", "Chino mandarín", "你好，你好吗？"),
    ("zh-TW", "Chino tradicional", "你好，你好嗎？"),
    ("ja", "Japonés", "こんにちは、お元気ですか？"),
    ("ko", "Coreano", "안녕하세요, 잘 지내세요?"),
    ("mn", "Mongol", "Сайн байна уу, та сайн уу?"),
    ("vi", "Vietnamita", "Xin chào, bạn khỏe không?"),
    ("id", "Indonesio", "Halo, apa kabar?"),
    ("ms", "Malayo", "Hai, apa khabar?"),
    ("tl", "Tagalo", "Kumusta, kamusta ka?"),
    ("sw", "Suajili", "Habari, unaendeleaje?"),
    ("af", "Afrikáans", "Hallo, hoe gaan dit met jou?"),
    ("am", "Amárico", "ሰላም፣ እንዴት ነህ?"),
    ("so", "Somalí", "Salaan, sidee tahay?"),
    ("ti", "Tigriña", "ሰላም፣ ከመይ ኣለኻ?"),
    ("xh", "Xhosa", "Molo, unjani?"),
    ("zu", "Zulú", "Sawubona, unjani?"),
    ("yo", "Yoruba", "Pẹ̀lẹ́, báwo ni?"),
    ("ig", "Igbo", "Ndewo, kedụ ka ị mere?"),
    ("ha", "Hausa", "Sannu, ya ya kake?"),
    ("mg", "Malgache", "Salama, manao ahoana ianao?"),
    ("fy", "Frisón occidental", "Hallo, hoe giet it mei dy?"),
    ("eu", "Euskera", "Kaixo, nola zaude?"),
    ("ca", "Catalán", "Hola, com estàs?"),
    ("gl", "Gallego", "Ola, como estás?"),
    ("qu", "Quechua", "Rimaykullayki, imaynallataq kachkanki?"),
    ("gn", "Guaraní", "Mba'éichapa, mba'éichapa reime?"),
    ("yrl", "Nheengatu", "Maí, maita ne reko?"),
    ("nah", "Náhuatl", "Pialli, quenin tica?"),
    ("oc", "Occitano", "Adieu, cossí vas?"),
    ("sc", "Sardo", "A tie, comente ses?"),
    ("rm", "Romanche", "Allegra, co vai?"),
    ("yi", "Yidis", "שלום, ווי ביסטו?"),
    ("ku", "Kurdo kurmanji", "Silav, tu çawa yî?"),
    ("ckb", "Kurdo soraní", "سڵاو، چۆنی؟"),
    ("tg", "Tayiko", "Салом, шумо чӣ хелед?"),
    ("kk", "Kazajo", "Сәлем, қалайсың?"),
    ("uz", "Uzbeko", "Salom, qalaysan?"),
    ("ky", "Kirguís", "Салам, кандайсың?"),
    ("tk", "Turcomano", "Salam, ýagdaýyň nähili?"),
    ("tt", "Tártaro", "Сәлам, хәлләрең ничек?"),
    ("lb", "Luxemburgués", "Moien, wéi geet et dir?"),
]
